version: "3.1"
services:

  app:
        build:
          context: ./
          dockerfile: Dockerfile
        working_dir: /var/www/html
        volumes:
          - ../:/var/www/html

  nginx:
    image: tutum/nginx
    ports:
      - "3002:80"
    links:
      - app
      - db
    volumes:
      - ./nginx/default:/etc/nginx/sites-available/default
      - ./nginx/default:/etc/nginx/sites-enabled/default

      - ./logs/nginx-access.log:/var/log/nginx/access.log
      - ./logs/nginx-error.log:/var/log/nginx/error.log


  db:
    image: mysql:5.7.22
    container_name: db
    ports:
          - "3333:3306"
    volumes:
      - '/var/interview:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tree
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    restart: unless-stopped